language: node_js
node_js:
  - "stable"
env:
  CODECLIMATE_REPO_TOKEN: 386c40bb4bbd6db04800251143b35c11f6e314259c906a3819c34febffaea9b8
before_install: yarn global add greenkeeper-lockfile@2
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - yarn lint
  - yarn typecheck
  - yarn test  
after_success:
  - './node_modules/.bin/nyc report --reporter=lcov'
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
notifications:
  email: false
